[build]
  publish = "."
  functions = "netlify/functions"
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_URL"

[build.environment]
  NODE_VERSION = "22"

[build.processing]
  [build.processing.css]
  [build.processing.html]
  [build.processing.images]
  [build.processing.js]

[functions]
  [functions."*"]
    node_bundler = "esbuild"
